name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        working-directory: programa
        run: gcc -Wall -Wextra -std=c11 -I./include main.c Cliente.c Config.c Estadistica.c Libro.c Pedido.c Utilidades.c cJSON.c Interfaz.c -o libreria
